services:
  - type: web
    name: my-ruby-app
    buildCommand: bundle install
    startCommand: bundle exec ruby app.rb
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: my-mysql-db
          alias: primary
      - key: DATABASE_USERNAME
        fromDatabase:
          name: my-mysql-db
          alias: primary
          property: username
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: my-mysql-db
          alias: primary
          property: password

databases:
  - name: my-mysql-db
    type: mysql
    plan: free