databases:
  - name: spree
    databaseName: spree
    user: spree

services:
  - type: web
    name: spree
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spree
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: spree_redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: ADMIN_EMAIL
        value: 'spree@example.com'
      - key: ADMIN_PASSWORD
        value: 'spree123'
  - type: redis
    name: spree_redis
    ipAllowList: [] # only allow internal connections

# databases:
#   - name: postgres
#     ipAllowList: []

# services:
#   - type: web
#     name: rails
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: bundle exec rails s
#     envVars:
#     - key: RAILS_MASTER_KEY
#       sync: false
#     - key: DATABASE_URL
#       fromDatabase:
#         name: postgres
#         property: connectionString
#   - type: redis
#     name: redis
#     ipAllowList: []
#     plan: free
#     maxmemoryPolicy: noeviction